# Spring
spring:
  config:
    import: optional:nacos:misu-account-prod.yml
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 10.8.0.22:8848
        # 命名空间
        namespace: prod
        # 组名
        group: DEFAULT_GROUP
        # 指定网卡
#        network-interface: tun0
      config:
        import-check:
          enabled: false
        # 配置中心地址
        server-addr: 10.8.0.22:8848
        # 命名空间
        namespace: prod
        # 组名
        group: DEFAULT_GROUP
        # 配置文件格式
        file-extension: yml
