# Tomcat
server:
  port: 30261
  servlet:
    context-path: /account

# Spring
spring:
  application:
    # 应用名称
    name: misu-account
  profiles:
    # 环境配置
    active: local

# Token配置，Nacos中可按环境覆盖
token:
  # 短期token有效期：1天
  expireTtl: 86400000
  # 长期刷新token有效期：30天
  refreshExpireTtl: 2592000000
